language: node_js

node_js:
  - "14"
  - "12"
  - "10"

branches:
  only:
    - master

env:
  - CODECOV_TOKEN="08fa8536-6220-46c7-a12a-4b8c19566fc4"

before_install:
  - npm i -g npm

script:
  - yarn global add codecov
  - yarn build
  - yarn test

after_success:
  - travis_retry codecov
